import { AreaPageData } from "@/components/AreaPageTemplate";

const commonPestsSanDiego = [
  "Argentine Ants & Fire Ants",
  "Black Widow Spiders",
  "Roof Rats & House Mice",
  "German & American Cockroaches",
  "Bed Bugs",
  "Fleas & Ticks",
  "Mosquitoes",
  "Earwigs & Silverfish",
];

function makeFAQs(city: string) {
  return [
    {
      question: `Do you offer same-day pest control in ${city}?`,
      answer: `Yes! We offer same-day service for most pest situations in ${city} and throughout San Diego County. Call us at (858) 878-2847 and we'll do our best to dispatch a technician the same day.`,
    },
    {
      question: `How much does pest control cost in ${city}?`,
      answer: `Pricing depends on the type of pest, size of your property, and level of infestation. We offer free inspections and quotes — call (858) 878-2847 or fill out our online form for a no-obligation estimate.`,
    },
    {
      question: `Are your pest control treatments safe in ${city} homes?`,
      answer: `Absolutely. We use eco-friendly, family and pet-safe products approved for residential use in California. Our technicians will walk you through any specific precautions before and after treatment.`,
    },
    {
      question: `Do you offer recurring pest control service in ${city}?`,
      answer: `Yes. We recommend quarterly preventative treatments for most ${city} homes. San Diego's mild climate means pests are active year-round, so regular service is the best way to stay ahead of infestations.`,
    },
  ];
}

export const areaPages: Record<string, AreaPageData> = {
  "la-jolla": {
    cityName: "La Jolla",
    slug: "la-jolla",
    intro: "Professional pest control in La Jolla, CA — trusted by homeowners throughout one of San Diego's most beautiful communities.",
    bodyParagraph: "La Jolla's coastal setting and lush landscaping create ideal conditions for ants, spiders, and rodents year-round. Neighbors Pest Solutions serves La Jolla homeowners with safe, effective pest treatments — whether it's a black widow problem in the garage or a rodent issue in the attic.",
    commonPests: commonPestsSanDiego,
    faqs: makeFAQs("La Jolla"),
  },
  "mira-mesa": {
    cityName: "Mira Mesa",
    slug: "mira-mesa",
    intro: "Fast, reliable pest control in Mira Mesa, CA. Protecting Mira Mesa families from ants, spiders, roaches, rodents, and more.",
    bodyParagraph: "Mira Mesa's warm inland climate makes it a hotspot for Argentine ants, cockroaches, and roof rats. Our Mira Mesa service covers full interior and exterior treatments for residential and commercial properties.",
    commonPests: commonPestsSanDiego,
    faqs: makeFAQs("Mira Mesa"),
  },
  "scripps-ranch": {
    cityName: "Scripps Ranch",
    slug: "scripps-ranch",
    intro: "Pest control services in Scripps Ranch, CA — protecting families near the eucalyptus forests from spiders, rodents, and seasonal pests.",
    bodyParagraph: "Scripps Ranch's proximity to open space and canyon systems means regular pressure from rodents, spiders, and insects. We provide customized treatment plans for Scripps Ranch homes, focusing on perimeter protection and entry point exclusion.",
    commonPests: [...commonPestsSanDiego, "Gophers & Ground Squirrels"],
    faqs: makeFAQs("Scripps Ranch"),
  },
  "clairemont": {
    cityName: "Clairemont",
    slug: "clairemont",
    intro: "Trusted pest control in Clairemont, CA — effective treatments for ants, spiders, roaches, rodents, and other common pests.",
    bodyParagraph: "Clairemont is one of San Diego's most established residential neighborhoods, with a mix of older homes that can be more susceptible to rodent entry and cockroach infestations. Our team has extensive experience treating Clairemont homes.",
    commonPests: commonPestsSanDiego,
    faqs: makeFAQs("Clairemont"),
  },
  "pacific-beach": {
    cityName: "Pacific Beach",
    slug: "pacific-beach",
    intro: "Pest control in Pacific Beach, CA — coastal pest problems solved fast by your local San Diego experts.",
    bodyParagraph: "Pacific Beach's coastal moisture and dense housing makes it a prime target for moisture-loving pests like silverfish, cockroaches, and earwigs. We offer targeted interior and exterior treatments for PB homes, condos, and rental properties.",
    commonPests: [...commonPestsSanDiego, "Silverfish & Earwigs"],
    faqs: makeFAQs("Pacific Beach"),
  },
  "carmel-valley": {
    cityName: "Carmel Valley",
    slug: "carmel-valley",
    intro: "Expert pest control in Carmel Valley, CA — keeping this premier San Diego community free from ants, spiders, rodents, and more.",
    bodyParagraph: "Carmel Valley's newer construction and landscaping can still attract significant ant and spider pressure, especially in the transition between rainy and dry seasons. We provide thorough preventative and corrective treatments for Carmel Valley homes.",
    commonPests: commonPestsSanDiego,
    faqs: makeFAQs("Carmel Valley"),
  },
  "mission-valley": {
    cityName: "Mission Valley",
    slug: "mission-valley",
    intro: "Pest control in Mission Valley, CA — residential and commercial treatments for the heart of San Diego.",
    bodyParagraph: "Mission Valley's mix of condos, apartments, and commercial properties experiences persistent cockroach, ant, and rodent pressure. We serve multi-unit properties, individual condos, and residential homes throughout Mission Valley.",
    commonPests: commonPestsSanDiego,
    faqs: makeFAQs("Mission Valley"),
  },
  "rancho-bernardo": {
    cityName: "Rancho Bernardo",
    slug: "rancho-bernardo",
    intro: "Pest control in Rancho Bernardo, CA — protecting Rancho Bernardo families from rodents, spiders, ants, and seasonal pests.",
    bodyParagraph: "Rancho Bernardo's location near Bernardo Mountain and open space preserves means regular pressure from rodents and spiders. We deliver comprehensive exclusion and treatment programs for RB homeowners.",
    commonPests: [...commonPestsSanDiego, "Gophers & Ground Squirrels"],
    faqs: makeFAQs("Rancho Bernardo"),
  },
  "rancho-penasquitos": {
    cityName: "Rancho Peñasquitos",
    slug: "rancho-penasquitos",
    intro: "Pest control in Rancho Peñasquitos, CA — professional treatments for this family-friendly San Diego community.",
    bodyParagraph: "Rancho Peñasquitos homeowners regularly deal with Argentine ants, roof rats, and occasional black widow infestations, especially in homes backing to canyon areas. Our team provides tailored treatment programs for the area.",
    commonPests: commonPestsSanDiego,
    faqs: makeFAQs("Rancho Peñasquitos"),
  },
  "point-loma": {
    cityName: "Point Loma",
    slug: "point-loma",
    intro: "Pest control in Point Loma, CA — protecting this historic San Diego peninsula from ants, spiders, rodents, and coastal pests.",
    bodyParagraph: "Point Loma's older homes and coastal location attract moisture pests and rodents. We offer preventative and corrective treatments for Point Loma residences, military housing, and commercial properties.",
    commonPests: commonPestsSanDiego,
    faqs: makeFAQs("Point Loma"),
  },
  "ocean-beach": {
    cityName: "Ocean Beach",
    slug: "ocean-beach",
    intro: "Pest control in Ocean Beach, CA — fast, eco-friendly treatments for OB homes and rentals.",
    bodyParagraph: "Ocean Beach's coastal humidity and older housing stock create favorable conditions for silverfish, cockroaches, and earwigs. We serve OB homeowners, renters, and property managers with responsive, thorough pest treatments.",
    commonPests: [...commonPestsSanDiego, "Silverfish & Earwigs"],
    faqs: makeFAQs("Ocean Beach"),
  },
  "north-park": {
    cityName: "North Park",
    slug: "north-park",
    intro: "Pest control in North Park, CA — keeping one of San Diego's hippest neighborhoods pest-free.",
    bodyParagraph: "North Park's older craftsman homes and dense urban environment make it a prime area for cockroach, rodent, and bed bug activity. We serve both residential and commercial properties throughout North Park and neighboring areas.",
    commonPests: commonPestsSanDiego,
    faqs: makeFAQs("North Park"),
  },
  "hillcrest": {
    cityName: "Hillcrest",
    slug: "hillcrest",
    intro: "Pest control in Hillcrest, CA — reliable treatments for San Diego's urban core.",
    bodyParagraph: "Hillcrest's dense urban setting and older building stock present unique pest challenges, from German cockroaches in restaurants and kitchens to rodents in older structures. We provide both residential and commercial pest solutions.",
    commonPests: commonPestsSanDiego,
    faqs: makeFAQs("Hillcrest"),
  },
  "downtown-san-diego": {
    cityName: "Downtown San Diego",
    slug: "downtown-san-diego",
    intro: "Pest control in Downtown San Diego, CA — professional treatments for condos, commercial properties, and residences.",
    bodyParagraph: "Downtown San Diego's high-density living and commercial activity create ideal conditions for cockroaches, bed bugs, and rodents. We serve condo buildings, restaurants, offices, and residential properties throughout the downtown core.",
    commonPests: commonPestsSanDiego,
    faqs: makeFAQs("Downtown San Diego"),
  },
  "poway": {
    cityName: "Poway",
    slug: "poway",
    intro: "Pest control in Poway, CA — protecting the 'City in the Country' from rodents, spiders, ants, and suburban pests.",
    bodyParagraph: "Poway's semi-rural setting and proximity to open space means consistent pressure from rodents, gophers, and spiders. We offer full exclusion and treatment programs for Poway homes, including perimeter protection and attic rodent exclusion.",
    commonPests: [...commonPestsSanDiego, "Gophers & Ground Squirrels"],
    faqs: makeFAQs("Poway"),
  },
  "chula-vista": {
    cityName: "Chula Vista",
    slug: "chula-vista",
    intro: "Pest control in Chula Vista, CA — San Diego County's second-largest city deserves top-tier pest protection.",
    bodyParagraph: "Chula Vista's warm inland climate and rapid residential growth attract ants, cockroaches, rodents, and mosquitoes. Our team provides comprehensive residential and commercial pest treatments throughout all Chula Vista neighborhoods.",
    commonPests: commonPestsSanDiego,
    faqs: makeFAQs("Chula Vista"),
  },
  "el-cajon": {
    cityName: "El Cajon",
    slug: "el-cajon",
    intro: "Pest control in El Cajon, CA — effective treatments for one of San Diego's hottest and most pest-active inland cities.",
    bodyParagraph: "El Cajon's hot, dry summers push pests indoors in large numbers — especially ants, cockroaches, and rodents. We provide responsive, thorough treatments for El Cajon homes and businesses.",
    commonPests: commonPestsSanDiego,
    faqs: makeFAQs("El Cajon"),
  },
  "santee": {
    cityName: "Santee",
    slug: "santee",
    intro: "Pest control in Santee, CA — protecting East San Diego County homes from rodents, ants, spiders, and more.",
    bodyParagraph: "Santee's suburban neighborhoods adjacent to open space experience ongoing pressure from roof rats, ants, and spiders. We deliver targeted exclusion and barrier treatments for Santee homeowners.",
    commonPests: commonPestsSanDiego,
    faqs: makeFAQs("Santee"),
  },
  "la-mesa": {
    cityName: "La Mesa",
    slug: "la-mesa",
    intro: "Pest control in La Mesa, CA — trusted treatments for the 'Jewel of the Hills' and surrounding neighborhoods.",
    bodyParagraph: "La Mesa's older residential homes and proximity to urban San Diego make it susceptible to cockroach, rodent, and ant infestations. We serve La Mesa homeowners with customized treatment plans and ongoing service programs.",
    commonPests: commonPestsSanDiego,
    faqs: makeFAQs("La Mesa"),
  },
  "national-city": {
    cityName: "National City",
    slug: "national-city",
    intro: "Pest control in National City, CA — professional treatments for residential and commercial properties.",
    bodyParagraph: "National City's dense urban environment and proximity to the bay create conditions favorable to cockroaches, rodents, and moisture pests. We provide thorough treatments for homes, apartments, and businesses throughout National City.",
    commonPests: commonPestsSanDiego,
    faqs: makeFAQs("National City"),
  },
  "spring-valley": {
    cityName: "Spring Valley",
    slug: "spring-valley",
    intro: "Pest control in Spring Valley, CA — effective treatments for this unincorporated community in San Diego County.",
    bodyParagraph: "Spring Valley's semi-rural character and older housing stock invite rodents, spiders, and ant colonies. Our team provides thorough inspections and customized treatment plans for Spring Valley residents.",
    commonPests: commonPestsSanDiego,
    faqs: makeFAQs("Spring Valley"),
  },
  "lakeside": {
    cityName: "Lakeside",
    slug: "lakeside",
    intro: "Pest control in Lakeside, CA — protecting East County families from pests year-round.",
    bodyParagraph: "Lakeside's rural-suburban mix and proximity to the San Diego River corridor means regular rodent, spider, and ant activity. We offer comprehensive residential pest programs for Lakeside homeowners.",
    commonPests: [...commonPestsSanDiego, "Gophers & Ground Squirrels"],
    faqs: makeFAQs("Lakeside"),
  },
  "solana-beach": {
    cityName: "Solana Beach",
    slug: "solana-beach",
    intro: "Pest control in Solana Beach, CA — right in our backyard. We're your true local experts.",
    bodyParagraph: "Neighbors Pest Solutions is headquartered in Solana Beach. We know this community because we live here. From ant infestations in coastal homes to rodent exclusion in older properties near the train station, we've treated it all.",
    commonPests: [...commonPestsSanDiego, "Silverfish & Earwigs"],
    faqs: makeFAQs("Solana Beach"),
  },
  "del-mar": {
    cityName: "Del Mar",
    slug: "del-mar",
    intro: "Pest control in Del Mar, CA — premium pest protection for one of San Diego's most prestigious coastal communities.",
    bodyParagraph: "Del Mar's luxury coastal properties and lush landscaping create ideal conditions for ants, spiders, and occasional rodent activity. We provide discreet, professional pest control that matches the standards Del Mar homeowners expect.",
    commonPests: commonPestsSanDiego,
    faqs: makeFAQs("Del Mar"),
  },
  "encinitas": {
    cityName: "Encinitas",
    slug: "encinitas",
    intro: "Pest control in Encinitas, CA — eco-conscious, effective treatments for this North County coastal community.",
    bodyParagraph: "Encinitas homeowners appreciate our commitment to eco-friendly, family-safe products — a perfect match for this community's environmental values. We provide comprehensive pest control for Encinitas homes, gardens, and businesses.",
    commonPests: commonPestsSanDiego,
    faqs: makeFAQs("Encinitas"),
  },
  "carlsbad": {
    cityName: "Carlsbad",
    slug: "carlsbad",
    intro: "Pest control in Carlsbad, CA — protecting North County's village-by-the-sea from ants, spiders, rodents, and more.",
    bodyParagraph: "Carlsbad's mix of coastal and inland properties, newer master-planned communities, and agricultural areas creates a diverse pest landscape. We provide tailored treatments for all types of Carlsbad properties.",
    commonPests: commonPestsSanDiego,
    faqs: makeFAQs("Carlsbad"),
  },
  "escondido": {
    cityName: "Escondido",
    slug: "escondido",
    intro: "Pest control in Escondido, CA — inland North County pest experts serving residential and commercial properties.",
    bodyParagraph: "Escondido's hot inland climate and proximity to open land drives high pest activity — particularly ants, cockroaches, and rodents during summer months. We provide fast, effective treatments for Escondido homes and businesses.",
    commonPests: [...commonPestsSanDiego, "Gophers & Ground Squirrels"],
    faqs: makeFAQs("Escondido"),
  },
  "san-marcos": {
    cityName: "San Marcos",
    slug: "san-marcos",
    intro: "Pest control in San Marcos, CA — protecting North County Inland families and businesses.",
    bodyParagraph: "San Marcos's rapidly growing residential communities and warm inland climate attract ants, rodents, and cockroaches. We serve new construction and established neighborhoods throughout San Marcos.",
    commonPests: commonPestsSanDiego,
    faqs: makeFAQs("San Marcos"),
  },
  "vista": {
    cityName: "Vista",
    slug: "vista",
    intro: "Pest control in Vista, CA — trusted treatments for North County Inland homeowners.",
    bodyParagraph: "Vista's mix of residential neighborhoods and agricultural surroundings creates unique pest challenges, including gophers, rodents, and regular ant pressure. Our Vista service covers comprehensive interior and exterior treatments.",
    commonPests: [...commonPestsSanDiego, "Gophers & Ground Squirrels"],
    faqs: makeFAQs("Vista"),
  },
  "oceanside": {
    cityName: "Oceanside",
    slug: "oceanside",
    intro: "Pest control in Oceanside, CA — North County's largest city deserves professional pest protection.",
    bodyParagraph: "Oceanside's coastal proximity and large residential population drive consistent pest activity across ants, spiders, fleas, and rodents. We serve Oceanside homeowners, military housing, and commercial properties with responsive, guaranteed treatments.",
    commonPests: [...commonPestsSanDiego, "Silverfish & Earwigs"],
    faqs: makeFAQs("Oceanside"),
  },
};
