import { ServicePageData } from "@/components/ServicePageTemplate";

export const servicePages: Record<string, ServicePageData> = {
  "ant-control": {
    slug: "ant-control",
    name: "Ant Control",
    heroHeading: "Ant Control San Diego, CA",
    heroSubheading: "Eliminate ant colonies at the source. We target Argentine ants, fire ants, carpenter ants, and all species common to San Diego homes.",
    heroImage: "/images/pest-control-san-diego.jpg",
    intro: "Ants are one of the most common pest problems in San Diego due to the warm, dry climate. When it gets hot or dry outside, ant colonies send foragers inside looking for food and water. A single ant trail can lead to hundreds of thousands of ants. Our technicians don't just spray the surface — we locate and treat the source colonies to deliver lasting results.",
    features: [
      { title: "Colony Source Treatment", desc: "We trace ant trails and treat the nest directly, not just the visible ants." },
      { title: "Interior & Exterior Barrier", desc: "A perimeter treatment prevents new ant scouts from entering your home." },
      { title: "Entry Point Sealing", desc: "We identify and recommend sealing of cracks, gaps, and utility penetrations." },
      { title: "Eco-Friendly Products", desc: "All products are family and pet safe once dry — we'll let you know when it's clear." },
    ],
    signs: [
      "Visible ant trails along walls, counters, or floors",
      "Finding ants in your kitchen, bathroom, or pantry",
      "Small piles of dirt or sand near walls and entry points",
      "Winged ants (swarmers) appearing inside your home",
      "Ant activity around your home's foundation",
      "Wood shavings or frass near wooden structures (carpenter ants)",
    ],
    process: [
      { step: "1", title: "Inspection", desc: "We inspect your property inside and out to identify the ant species and locate nesting sites." },
      { step: "2", title: "Treatment", desc: "We apply targeted bait, gel, and residual treatments at entry points and nest locations." },
      { step: "3", title: "Prevention", desc: "Exterior barrier application and recommendations to prevent future ant activity." },
    ],
    faqs: [
      { question: "How long does ant treatment take to work?", answer: "Most ant treatments show results within 24–72 hours. Colony baits may take 1–2 weeks to fully eliminate a colony, which is normal and expected." },
      { question: "Are ants dangerous?", answer: "Most ant species are nuisance pests, but fire ants can sting and cause allergic reactions, and carpenter ants can damage wood structures over time." },
      { question: "Why do I keep getting ants every year?", answer: "San Diego's climate makes ant pressure a year-round issue, especially in late summer and fall. A quarterly service plan keeps colonies from re-establishing." },
      { question: "Is the treatment safe for my pets?", answer: "Yes. We use family and pet-safe products. Your technician will advise on any brief re-entry period after treatment." },
    ],
    relatedServices: [
      { name: "Cockroach Control", slug: "cockroach-control" },
      { name: "Spider Control", slug: "spider-control" },
      { name: "Carpenter Ant Control", slug: "carpenter-ant-control" },
    ],
  },

  "bed-bug-control": {
    slug: "bed-bug-control",
    name: "Bed Bug Control",
    heroHeading: "Bed Bug Treatment San Diego, CA",
    heroSubheading: "Fast, thorough bed bug elimination using proven heat and chemical treatments. We won't rest until you can.",
    heroImage: "/images/pest-control-san-diego.jpg",
    intro: "Bed bugs are one of the most stressful and difficult pest infestations to deal with. They hide in mattresses, headboards, furniture, and even electrical outlets. Over-the-counter products rarely work against established infestations. Our licensed technicians use a combination of targeted chemical treatments and professional-grade methods to eliminate bed bugs at every life stage — including eggs.",
    features: [
      { title: "Thorough Inspection", desc: "We inspect all potential harborage areas including mattresses, box springs, headboards, sofas, and baseboards." },
      { title: "Multi-Method Treatment", desc: "Residual insecticide applied to all harborage zones for complete elimination." },
      { title: "Follow-Up Visits", desc: "Re-inspection and retreatment as needed to catch any surviving eggs." },
      { title: "Prevention Guidance", desc: "We explain how to reduce re-infestation risk when traveling or purchasing used furniture." },
    ],
    signs: [
      "Waking up with unexplained bites or welts in a line or cluster",
      "Small blood stains or dark spots on your sheets or mattress",
      "Tiny shed skins or egg casings on or near your bed",
      "A sweet, musty odor in your bedroom",
      "Visible bed bugs — apple seed-sized, reddish-brown insects",
      "Itching and skin irritation that worsens at night",
    ],
    process: [
      { step: "1", title: "Inspection", desc: "A thorough inspection of all bedrooms, furniture, and adjacent areas to confirm infestation and assess severity." },
      { step: "2", title: "Treatment", desc: "Residual chemical treatment applied to all harborage sites, mattress seams, box springs, furniture, and baseboards." },
      { step: "3", title: "Follow-Up", desc: "Return visit to re-inspect, verify elimination, and re-treat any active areas." },
    ],
    faqs: [
      { question: "How long does bed bug treatment take?", answer: "A single treatment visit typically takes 2–4 hours depending on home size. We recommend a follow-up visit 2 weeks later to treat any newly hatched eggs." },
      { question: "Do I need to throw away my mattress?", answer: "Usually not. Most mattresses can be saved with a proper encasement after treatment. We'll advise you on a case-by-case basis." },
      { question: "How do I prepare for bed bug treatment?", answer: "We'll provide a full preparation checklist before your appointment. This typically includes stripping bedding, washing and drying linens on high heat, and removing clutter." },
      { question: "Can bed bugs spread through my walls?", answer: "Yes, in multi-unit buildings bed bugs can spread between units. We recommend treating all adjoining units if you're in an apartment or condo." },
    ],
    relatedServices: [
      { name: "Spider Control", slug: "spider-control" },
      { name: "Flea Control", slug: "flea-control" },
      { name: "Mite Control", slug: "mite-control" },
    ],
  },

  "spider-control": {
    slug: "spider-control",
    name: "Spider Control",
    heroHeading: "Spider Control San Diego, CA",
    heroSubheading: "Keep black widows, brown recluses, and common house spiders out of your home with targeted spider treatments.",
    heroImage: "/images/pest-control-san-diego.jpg",
    intro: "San Diego is home to a wide variety of spider species — most harmless, but some dangerous. Black widows are common in Southern California and can pose a real health risk, especially in garages, sheds, and children's play areas. Our spider treatments target webs, nesting areas, and entry points to keep spiders from moving in.",
    features: [
      { title: "Web Removal", desc: "We knock down and remove existing webs around your home's exterior during each visit." },
      { title: "Residual Perimeter Treatment", desc: "We apply a residual treatment around your foundation, eaves, windows, and doors." },
      { title: "Black Widow Focus", desc: "Extra attention to dark, sheltered spots — garages, sheds, play equipment — where black widows hide." },
      { title: "Interior Spot Treatments", desc: "Treatment of corners, baseboards, and utility rooms where spiders enter and nest." },
    ],
    signs: [
      "Webs appearing in corners, eaves, or garages",
      "Egg sacs attached to surfaces or inside webs",
      "Visible black widow webs — irregular, tangled, near the ground",
      "Frequent spider sightings inside your home",
      "Spider bites or suspected bites on family members",
      "Large population of other insects (spiders follow their prey)",
    ],
    process: [
      { step: "1", title: "Inspection", desc: "We inspect your property for webs, nesting sites, and entry points, with special attention to black widow habitat." },
      { step: "2", title: "Web Removal & Treatment", desc: "We knock down webs and apply residual treatment to the exterior perimeter, eaves, garage, and interior entry points." },
      { step: "3", title: "Ongoing Protection", desc: "Quarterly service keeps spider populations controlled and webs from re-establishing." },
    ],
    faqs: [
      { question: "Are black widows common in San Diego?", answer: "Yes. Black widows are one of the most common venomous spiders in Southern California and are frequently found in garages, sheds, and around landscaping." },
      { question: "Is spider treatment safe around kids?", answer: "Absolutely. All products we use are labeled safe for residential use and are pet and family safe once dry." },
      { question: "How often should I have spider treatment?", answer: "Quarterly treatments are recommended for San Diego homes, as spiders are active year-round in the Southern California climate." },
      { question: "Can you treat for brown recluse spiders?", answer: "Yes, though brown recluses are less common in San Diego than black widows. We inspect and treat for both. Call us if you suspect a brown recluse infestation." },
    ],
    relatedServices: [
      { name: "Ant Control", slug: "ant-control" },
      { name: "Cockroach Control", slug: "cockroach-control" },
      { name: "Mite Control", slug: "mite-control" },
    ],
  },

  "rodent-control": {
    slug: "rodent-control",
    name: "Rodent Control",
    heroHeading: "Rodent Control San Diego, CA",
    heroSubheading: "Remove rats and mice from your home with comprehensive exclusion, trapping, and sanitation services.",
    heroImage: "/images/pest-control-san-diego.jpg",
    intro: "Rats and mice are a serious problem in San Diego County. Roof rats are especially common in urban and suburban neighborhoods, accessing homes through trees, utility lines, and gaps in the roofline. Rodents contaminate food, damage wiring, and carry diseases. Our rodent control program doesn't just set traps — we seal your home against re-entry so the problem doesn't return.",
    features: [
      { title: "Entry Point Exclusion", desc: "We identify and seal all gaps, holes, and entry points rats and mice use to get into your home." },
      { title: "Trap Placement & Monitoring", desc: "Strategic interior and exterior trap placement with regular monitoring and removal." },
      { title: "Bait Station Program", desc: "Tamper-resistant exterior bait stations to eliminate rodents before they enter your structure." },
      { title: "Sanitation Recommendations", desc: "We advise on food storage, yard maintenance, and vegetation management to reduce rodent harborage." },
    ],
    signs: [
      "Scratching or scurrying sounds in walls, attic, or ceiling at night",
      "Rodent droppings in cabinets, drawers, or along walls",
      "Gnaw marks on food packaging, wiring, or wood",
      "Nesting material — shredded paper or fabric — in hidden areas",
      "Grease marks along walls or baseboards",
      "Visible rodents or burrows in your yard",
    ],
    process: [
      { step: "1", title: "Inspection", desc: "Complete interior and exterior inspection to identify entry points, harborage areas, and infestation severity." },
      { step: "2", title: "Exclusion & Trapping", desc: "We seal entry points and deploy targeted traps and exterior bait stations." },
      { step: "3", title: "Follow-Up & Monitoring", desc: "Return visit to check traps, confirm elimination, and verify exclusion work is holding." },
    ],
    faqs: [
      { question: "What kind of rodents are common in San Diego?", answer: "Roof rats are the most common in San Diego, followed by Norway rats and house mice. We identify and treat for all species." },
      { question: "Are rodent bait stations safe for pets?", answer: "We use tamper-resistant bait stations that are designed to prevent access by pets and children. We'll review placement with you at the time of service." },
      { question: "How did rodents get into my home?", answer: "Roof rats commonly enter through gaps in the roofline, attic vents, and where utility lines penetrate the structure. Even a hole the size of a quarter is enough." },
      { question: "How long does rodent treatment take?", answer: "Most active infestations are resolved within 2–4 weeks, depending on severity. Exclusion work is done on the first visit. Follow-up visits confirm elimination." },
    ],
    relatedServices: [
      { name: "Ant Control", slug: "ant-control" },
      { name: "Cockroach Control", slug: "cockroach-control" },
      { name: "Spider Control", slug: "spider-control" },
    ],
  },

  "cockroach-control": {
    slug: "cockroach-control",
    name: "Cockroach Control",
    heroHeading: "Cockroach Exterminator San Diego, CA",
    heroSubheading: "Fast, effective cockroach elimination for San Diego homes. We target German, American, and Oriental cockroach infestations at the source.",
    heroImage: "/images/pest-control-san-diego.jpg",
    intro: "Cockroaches are among the most resilient and fastest-reproducing pests. A small problem can become a full infestation within weeks. They contaminate food, spread bacteria, and trigger asthma and allergies. Our cockroach treatments go beyond surface spraying — we use targeted gel baits, growth regulators, and residual products applied to harborage zones for complete elimination.",
    features: [
      { title: "Gel Bait Placement", desc: "Applied inside cabinets, under appliances, and in cracks where cockroaches harbor." },
      { title: "Insect Growth Regulator", desc: "Prevents juvenile cockroaches from maturing and reproducing, breaking the life cycle." },
      { title: "Residual Treatment", desc: "Applied to harborage zones, baseboards, and entry points for ongoing protection." },
      { title: "Sanitation Guidance", desc: "Advice on food storage, moisture control, and clutter reduction to eliminate harborage conditions." },
    ],
    signs: [
      "Cockroaches seen during the day (usually indicates heavy infestation)",
      "Musty, oily odor in kitchen or bathrooms",
      "Droppings resembling coffee grounds or black pepper near food areas",
      "Egg casings (oothecae) in dark corners or behind appliances",
      "Smear marks on walls near moisture sources",
      "Dead cockroaches in kitchen or bathroom areas",
    ],
    process: [
      { step: "1", title: "Inspection", desc: "We inspect kitchens, bathrooms, utility areas, and all appliances to determine species and infestation level." },
      { step: "2", title: "Treatment", desc: "Gel bait, growth regulator, and residual insecticide applied to all harborage zones and entry points." },
      { step: "3", title: "Follow-Up", desc: "Re-inspection to confirm elimination and retreat as needed — often included in our service guarantee." },
    ],
    faqs: [
      { question: "How fast can cockroaches reproduce?", answer: "German cockroaches can go from 1 to 1,000 insects in about 3 months. Early treatment is critical." },
      { question: "Why do I only see cockroaches at night?", answer: "Cockroaches are nocturnal. If you're seeing them during the day, it usually indicates an overcrowded, established infestation." },
      { question: "Do I need to vacate my home for cockroach treatment?", answer: "Usually not. We use targeted gel baits that are safe for occupied homes. Your technician will advise on specific precautions." },
      { question: "How long until cockroaches are gone?", answer: "Most infestations show dramatic improvement within 1–2 weeks. A follow-up visit 2–4 weeks later ensures the infestation is fully resolved." },
    ],
    relatedServices: [
      { name: "Ant Control", slug: "ant-control" },
      { name: "Rodent Control", slug: "rodent-control" },
      { name: "Spider Control", slug: "spider-control" },
    ],
  },

  "mosquito-control": {
    slug: "mosquito-control",
    name: "Mosquito Control",
    heroHeading: "Mosquito Control San Diego, CA",
    heroSubheading: "Reclaim your outdoor spaces with professional mosquito barrier treatments that dramatically reduce mosquito populations.",
    heroImage: "/images/pest-control-san-diego.jpg",
    intro: "San Diego's warm, humid microclimates — especially near canyons, parks, and coastal areas — can produce significant mosquito populations. Beyond the nuisance, mosquitoes can transmit West Nile virus and other diseases. Our mosquito control program combines barrier sprays with source reduction to reduce mosquito populations by up to 90% in treated areas.",
    features: [
      { title: "Barrier Spray Treatment", desc: "Residual insecticide applied to vegetation, shrubbery, and resting sites around your yard." },
      { title: "Breeding Site Reduction", desc: "We identify and treat standing water sources where mosquitoes lay eggs on your property." },
      { title: "Larvicide Treatment", desc: "BTi larvicide applied to water features and drains to prevent larvae from developing." },
      { title: "Recurring Programs", desc: "Monthly or bi-monthly service keeps mosquito populations controlled throughout the season." },
    ],
    signs: [
      "Being bitten repeatedly when spending time outdoors",
      "Mosquitoes visible in shaded, vegetation-heavy areas of your yard",
      "Standing water in pots, gutters, bird baths, or low spots",
      "Buzzing sounds at dusk and dawn",
      "Mosquito larvae (wrigglers) visible in standing water",
      "Increased mosquito activity following rain",
    ],
    process: [
      { step: "1", title: "Inspection", desc: "We survey your property for adult mosquito resting sites and breeding locations." },
      { step: "2", title: "Treatment", desc: "Barrier spray applied to all vegetation and resting areas, plus breeding site treatment." },
      { step: "3", title: "Ongoing Protection", desc: "Monthly retreatments maintain protection throughout the mosquito season." },
    ],
    faqs: [
      { question: "How quickly does mosquito treatment work?", answer: "The barrier spray begins working immediately and provides 3–4 weeks of residual protection. You'll notice a significant reduction within 24–48 hours." },
      { question: "Is mosquito treatment safe for kids and pets?", answer: "Yes. Products are approved for residential use and safe once the treatment has dried, typically 30–45 minutes." },
      { question: "What can I do to reduce mosquitoes myself?", answer: "Empty standing water weekly (pots, gutters, bird baths, pet bowls). Trim overgrown vegetation and keep your lawn mowed." },
      { question: "Do you treat for Aedes mosquitoes?", answer: "Yes. We treat for all mosquito species present in San Diego, including Aedes aegypti (tiger mosquito), which can transmit Zika and dengue." },
    ],
    relatedServices: [
      { name: "Tick Control", slug: "tick-control" },
      { name: "Flea Control", slug: "flea-control" },
      { name: "Spider Control", slug: "spider-control" },
    ],
  },

  "flea-control": {
    slug: "flea-control",
    name: "Flea Control",
    heroHeading: "Flea Control San Diego, CA",
    heroSubheading: "Complete flea elimination for your home and yard using treatments timed with the flea life cycle.",
    heroImage: "/images/pest-control-san-diego.jpg",
    intro: "Fleas are more than just an itch — they can cause tapeworm infections, flea allergy dermatitis, and in severe cases, anemia. San Diego's mild climate means fleas can be active year-round. Effective flea control requires treating the home, yard, and your pets simultaneously — treating only one area allows fleas to reinfest from untreated sources. Our program covers all three.",
    features: [
      { title: "Interior Treatment", desc: "Residual insecticide and IGR applied to carpets, baseboards, upholstery, and pet bedding areas." },
      { title: "Exterior Treatment", desc: "Yard treatment targeting shaded areas where fleas rest and reproduce." },
      { title: "Insect Growth Regulator", desc: "Prevents flea eggs and larvae from developing, breaking the life cycle for lasting control." },
      { title: "Pet Treatment Coordination", desc: "We'll advise you on coordinating with your vet for proper on-pet flea treatment at the same time." },
    ],
    signs: [
      "Pets scratching, biting, or over-grooming",
      "Seeing tiny jumping insects on your pets, carpet, or furniture",
      "Small red bites on your ankles or lower legs",
      "Flea dirt (black pepper-like specks) on pet bedding or carpets",
      "Pets shaking their heads frequently",
      "Finding fleas on yourself after sitting on the floor",
    ],
    process: [
      { step: "1", title: "Inspection", desc: "We inspect all interior areas and the yard to determine flea harborage zones and infestation severity." },
      { step: "2", title: "Treatment", desc: "Simultaneous interior and exterior treatment with residual insecticide and IGR." },
      { step: "3", title: "Follow-Up", desc: "A follow-up treatment 2–3 weeks later addresses fleas emerging from eggs laid before treatment." },
    ],
    faqs: [
      { question: "Why do fleas come back after treatment?", answer: "Flea eggs take 1–3 weeks to hatch and are resistant to insecticides. A follow-up treatment 2–3 weeks after the first is essential to catch the new hatch." },
      { question: "Do I need to treat my pets too?", answer: "Yes. A full flea elimination requires treating the environment AND your pets. Consult your veterinarian for the appropriate on-pet treatment." },
      { question: "Do I need to leave my home during treatment?", answer: "Yes, we ask you, your family, and your pets to vacate for 2–3 hours during and after treatment to allow products to dry and settle." },
      { question: "Can fleas survive without pets?", answer: "Yes. Fleas can persist in carpets, furniture, and yards for months without a host. We treat the environment, not just where pets sleep." },
    ],
    relatedServices: [
      { name: "Tick Control", slug: "tick-control" },
      { name: "Mosquito Control", slug: "mosquito-control" },
      { name: "Spider Control", slug: "spider-control" },
    ],
  },

  "tick-control": {
    slug: "tick-control",
    name: "Tick Control",
    heroHeading: "Tick Control San Diego, CA",
    heroSubheading: "Protect your family and pets from tick-borne illness with professional yard and perimeter tick treatments.",
    heroImage: "/images/pest-control-san-diego.jpg",
    intro: "Ticks are a growing concern in San Diego County, particularly in neighborhoods near canyons, nature preserves, and chaparral. Western black-legged ticks (deer ticks) in our region can carry Lyme disease. Our tick control treatments target the vegetation, leaf litter, and shaded areas around your property where ticks wait for a host.",
    features: [
      { title: "Perimeter & Yard Treatment", desc: "Residual treatment applied to the tick 'transition zone' — where your lawn meets vegetation, brush, and fencing." },
      { title: "Vegetation Treatment", desc: "Treatment of low-growing shrubs, ground cover, and shaded areas where ticks harbor." },
      { title: "Recurring Protection", desc: "Seasonal or monthly service for properties near canyons, trails, or heavily wooded areas." },
      { title: "Prevention Guidance", desc: "Advice on landscaping practices and personal protection to minimize tick exposure." },
    ],
    signs: [
      "Finding ticks on yourself, children, or pets after outdoor activity",
      "Living near canyons, trails, or heavily vegetated areas",
      "Pets frequently coming in from outdoor areas",
      "Finding engorged ticks on animals or family members",
      "Skin rashes or bull's-eye pattern following an outdoor excursion",
      "Wildlife (deer, rabbits) frequently in your yard",
    ],
    process: [
      { step: "1", title: "Property Assessment", desc: "We walk your property to identify tick habitat — shaded areas, leaf litter, lawn edges, and vegetation zones." },
      { step: "2", title: "Targeted Treatment", desc: "Residual insecticide applied to all tick harborage areas and the lawn-vegetation transition zone." },
      { step: "3", title: "Ongoing Program", desc: "Monthly or bi-monthly retreatments for properties in high-risk areas near canyons or wildlands." },
    ],
    faqs: [
      { question: "What tick species are in San Diego?", answer: "Western black-legged ticks (potential Lyme carriers), American dog ticks, and brown dog ticks are most common in San Diego County." },
      { question: "When is tick season in San Diego?", answer: "Ticks are active year-round in San Diego's mild climate, but peak activity is typically from April through July, with a secondary peak in fall." },
      { question: "Is tick treatment safe for dogs?", answer: "Yes. Our treatments are safe for pets once dry, typically 30–45 minutes. We'll advise you on keeping pets off treated areas during the drying period." },
      { question: "How do I check for ticks?", answer: "After outdoor activity, check the scalp, behind ears, under arms, behind knees, and around the waistline. Shower within 2 hours of coming inside." },
    ],
    relatedServices: [
      { name: "Flea Control", slug: "flea-control" },
      { name: "Mosquito Control", slug: "mosquito-control" },
      { name: "Spider Control", slug: "spider-control" },
    ],
  },
};
