import { ServicePageData } from "@/components/ServicePageTemplate";

export const servicePages: Record<string, ServicePageData> = {
  "ant-control": {
    slug: "ant-control",
    name: "Ant Control",
    heroHeading: "Ant Control San Diego, CA",
    heroSubheading: "Eliminate ant colonies at the source. We target Argentine ants, fire ants, carpenter ants, and all species common to San Diego homes.",
    heroImage: "/images/ants-windowsill.jpg",
    intro: "Ants are one of the most common pest problems in San Diego due to the warm, dry climate. When it gets hot or dry outside, ant colonies send foragers inside looking for food and water. A single ant trail can lead to hundreds of thousands of ants. Our technicians don't just spray the surface, we locate and treat the source colonies to deliver lasting results.",
    features: [
      { title: "Colony Source Treatment", desc: "We trace ant trails and treat the nest directly, not just the visible ants." },
      { title: "Interior & Exterior Barrier", desc: "A perimeter treatment prevents new ant scouts from entering your home." },
      { title: "Entry Point Sealing", desc: "We identify and recommend sealing of cracks, gaps, and utility penetrations." },
      { title: "Eco-Friendly Products", desc: "All products are family and pet safe once dry, we'll let you know when it's clear." },
    ],
    signs: [
      "Visible ant trails along walls, counters, or floors",
      "Finding ants in your kitchen, bathroom, or pantry",
      "Small piles of dirt or sand near walls and entry points",
      "Winged ants (swarmers) appearing inside your home",
      "Ant activity around your home's foundation",
      "Wood shavings or frass near wooden structures (carpenter ants)",
    ],
    process: [
      { step: "1", title: "Inspection", desc: "We inspect your property inside and out to identify the ant species and locate nesting sites." },
      { step: "2", title: "Treatment", desc: "We apply targeted bait, gel, and residual treatments at entry points and nest locations." },
      { step: "3", title: "Prevention", desc: "Exterior barrier application and recommendations to prevent future ant activity." },
    ],
    faqs: [
      { question: "How long does ant treatment take to work?", answer: "Most ant treatments show results within 24–72 hours. Colony baits may take 1–2 weeks to fully eliminate a colony, which is normal and expected." },
      { question: "Are ants dangerous?", answer: "Most ant species are nuisance pests, but fire ants can sting and cause allergic reactions, and carpenter ants can damage wood structures over time." },
      { question: "Why do I keep getting ants every year?", answer: "San Diego's climate makes ant pressure a year-round issue, especially in late summer and fall. A quarterly service plan keeps colonies from re-establishing." },
      { question: "Is the treatment safe for my pets?", answer: "Yes. We use family and pet-safe products. Your technician will advise on any brief re-entry period after treatment." },
    ],
    relatedServices: [
      { name: "Cockroach Control", slug: "cockroach-control" },
      { name: "Spider Control", slug: "spider-control" },
      { name: "Carpenter Ant Control", slug: "carpenter-ant-control" },
    ],
  },

  "bed-bug-control": {
    slug: "bed-bug-control",
    name: "Bed Bug Control",
    heroHeading: "Bed Bug Treatment San Diego, CA",
    heroSubheading: "Fast, thorough bed bug elimination using proven heat and chemical treatments. We won't rest until you can.",
    heroImage: "/images/technician-spraying.jpg",
    intro: "Bed bugs are one of the most stressful and difficult pest infestations to deal with. They hide in mattresses, headboards, furniture, and even electrical outlets. Over-the-counter products rarely work against established infestations. Our licensed technicians use a combination of targeted chemical treatments and professional-grade methods to eliminate bed bugs at every life stage, including eggs.",
    features: [
      { title: "Thorough Inspection", desc: "We inspect all potential harborage areas including mattresses, box springs, headboards, sofas, and baseboards." },
      { title: "Multi-Method Treatment", desc: "Residual insecticide applied to all harborage zones for complete elimination." },
      { title: "Follow-Up Visits", desc: "Re-inspection and retreatment as needed to catch any surviving eggs." },
      { title: "Prevention Guidance", desc: "We explain how to reduce re-infestation risk when traveling or purchasing used furniture." },
    ],
    signs: [
      "Waking up with unexplained bites or welts in a line or cluster",
      "Small blood stains or dark spots on your sheets or mattress",
      "Tiny shed skins or egg casings on or near your bed",
      "A sweet, musty odor in your bedroom",
      "Visible bed bugs, apple seed-sized, reddish-brown insects",
      "Itching and skin irritation that worsens at night",
    ],
    process: [
      { step: "1", title: "Inspection", desc: "A thorough inspection of all bedrooms, furniture, and adjacent areas to confirm infestation and assess severity." },
      { step: "2", title: "Treatment", desc: "Residual chemical treatment applied to all harborage sites, mattress seams, box springs, furniture, and baseboards." },
      { step: "3", title: "Follow-Up", desc: "Return visit to re-inspect, verify elimination, and re-treat any active areas." },
    ],
    faqs: [
      { question: "How long does bed bug treatment take?", answer: "A single treatment visit typically takes 2–4 hours depending on home size. We recommend a follow-up visit 2 weeks later to treat any newly hatched eggs." },
      { question: "Do I need to throw away my mattress?", answer: "Usually not. Most mattresses can be saved with a proper encasement after treatment. We'll advise you on a case-by-case basis." },
      { question: "How do I prepare for bed bug treatment?", answer: "We'll provide a full preparation checklist before your appointment. This typically includes stripping bedding, washing and drying linens on high heat, and removing clutter." },
      { question: "Can bed bugs spread through my walls?", answer: "Yes, in multi-unit buildings bed bugs can spread between units. We recommend treating all adjoining units if you're in an apartment or condo." },
    ],
    relatedServices: [
      { name: "Spider Control", slug: "spider-control" },
      { name: "Flea Control", slug: "flea-control" },
      { name: "Cockroach Control", slug: "cockroach-control" },
    ],
  },

  "spider-control": {
    slug: "spider-control",
    name: "Spider Control",
    heroHeading: "Spider Control San Diego, CA",
    heroSubheading: "Keep black widows, brown recluses, and common house spiders out of your home with targeted spider treatments.",
    heroImage: "/images/technician-webs.jpg",
    intro: "San Diego is home to a wide variety of spider species, most harmless, but some dangerous. Black widows are common in Southern California and can pose a real health risk, especially in garages, sheds, and children's play areas. Our spider treatments target webs, nesting areas, and entry points to keep spiders from moving in.",
    features: [
      { title: "Web Removal", desc: "We knock down and remove existing webs around your home's exterior during each visit." },
      { title: "Residual Perimeter Treatment", desc: "We apply a residual treatment around your foundation, eaves, windows, and doors." },
      { title: "Black Widow Focus", desc: "Extra attention to dark, sheltered spots, garages, sheds, play equipment, where black widows hide." },
      { title: "Interior Spot Treatments", desc: "Treatment of corners, baseboards, and utility rooms where spiders enter and nest." },
    ],
    signs: [
      "Webs appearing in corners, eaves, or garages",
      "Egg sacs attached to surfaces or inside webs",
      "Visible black widow webs, irregular, tangled, near the ground",
      "Frequent spider sightings inside your home",
      "Spider bites or suspected bites on family members",
      "Large population of other insects (spiders follow their prey)",
    ],
    process: [
      { step: "1", title: "Inspection", desc: "We inspect your property for webs, nesting sites, and entry points, with special attention to black widow habitat." },
      { step: "2", title: "Web Removal & Treatment", desc: "We knock down webs and apply residual treatment to the exterior perimeter, eaves, garage, and interior entry points." },
      { step: "3", title: "Ongoing Protection", desc: "Quarterly service keeps spider populations controlled and webs from re-establishing." },
    ],
    faqs: [
      { question: "Are black widows common in San Diego?", answer: "Yes. Black widows are one of the most common venomous spiders in Southern California and are frequently found in garages, sheds, and around landscaping." },
      { question: "Is spider treatment safe around kids?", answer: "Absolutely. All products we use are labeled safe for residential use and are pet and family safe once dry." },
      { question: "How often should I have spider treatment?", answer: "Quarterly treatments are recommended for San Diego homes, as spiders are active year-round in the Southern California climate." },
      { question: "Can you treat for brown recluse spiders?", answer: "Yes, though brown recluses are less common in San Diego than black widows. We inspect and treat for both. Call us if you suspect a brown recluse infestation." },
    ],
    relatedServices: [
      { name: "Ant Control", slug: "ant-control" },
      { name: "Cockroach Control", slug: "cockroach-control" },
      { name: "Earwig Control", slug: "earwig-control" },
    ],
  },

  "rodent-control": {
    slug: "rodent-control",
    name: "Rodent Control",
    heroHeading: "Rodent Control San Diego, CA",
    heroSubheading: "Remove rats and mice from your home with comprehensive exclusion, trapping, and sanitation services.",
    heroImage: "/images/technician-walkway.jpg",
    intro: "Rats and mice are a serious problem in San Diego County. Roof rats are especially common in urban and suburban neighborhoods, accessing homes through trees, utility lines, and gaps in the roofline. Rodents contaminate food, damage wiring, and carry diseases. Our rodent control program doesn't just set traps, we seal your home against re-entry so the problem doesn't return.",
    features: [
      { title: "Entry Point Exclusion", desc: "We identify and seal all gaps, holes, and entry points rats and mice use to get into your home." },
      { title: "Trap Placement & Monitoring", desc: "Strategic interior and exterior trap placement with regular monitoring and removal." },
      { title: "Bait Station Program", desc: "Tamper-resistant exterior bait stations to eliminate rodents before they enter your structure." },
      { title: "Sanitation Recommendations", desc: "We advise on food storage, yard maintenance, and vegetation management to reduce rodent harborage." },
    ],
    signs: [
      "Scratching or scurrying sounds in walls, attic, or ceiling at night",
      "Rodent droppings in cabinets, drawers, or along walls",
      "Gnaw marks on food packaging, wiring, or wood",
      "Nesting material, shredded paper or fabric, in hidden areas",
      "Grease marks along walls or baseboards",
      "Visible rodents or burrows in your yard",
    ],
    process: [
      { step: "1", title: "Inspection", desc: "Complete interior and exterior inspection to identify entry points, harborage areas, and infestation severity." },
      { step: "2", title: "Exclusion & Trapping", desc: "We seal entry points and deploy targeted traps and exterior bait stations." },
      { step: "3", title: "Follow-Up & Monitoring", desc: "Return visit to check traps, confirm elimination, and verify exclusion work is holding." },
    ],
    faqs: [
      { question: "What kind of rodents are common in San Diego?", answer: "Roof rats are the most common in San Diego, followed by Norway rats and house mice. We identify and treat for all species." },
      { question: "Are rodent bait stations safe for pets?", answer: "We use tamper-resistant bait stations that are designed to prevent access by pets and children. We'll review placement with you at the time of service." },
      { question: "How did rodents get into my home?", answer: "Roof rats commonly enter through gaps in the roofline, attic vents, and where utility lines penetrate the structure. Even a hole the size of a quarter is enough." },
      { question: "How long does rodent treatment take?", answer: "Most active infestations are resolved within 2–4 weeks, depending on severity. Exclusion work is done on the first visit. Follow-up visits confirm elimination." },
    ],
    relatedServices: [
      { name: "Ant Control", slug: "ant-control" },
      { name: "Cockroach Control", slug: "cockroach-control" },
      { name: "Spider Control", slug: "spider-control" },
    ],
  },

  "cockroach-control": {
    slug: "cockroach-control",
    name: "Cockroach Control",
    heroHeading: "Cockroach Exterminator San Diego, CA",
    heroSubheading: "Fast, effective cockroach elimination for San Diego homes. We target German, American, and Oriental cockroach infestations at the source.",
    heroImage: "/images/cockroach.jpg",
    intro: "Cockroaches are among the most resilient and fastest-reproducing pests. A small problem can become a full infestation within weeks. They contaminate food, spread bacteria, and trigger asthma and allergies. Our cockroach treatments go beyond surface spraying, we use targeted gel baits, growth regulators, and residual products applied to harborage zones for complete elimination.",
    features: [
      { title: "Gel Bait Placement", desc: "Applied inside cabinets, under appliances, and in cracks where cockroaches harbor." },
      { title: "Insect Growth Regulator", desc: "Prevents juvenile cockroaches from maturing and reproducing, breaking the life cycle." },
      { title: "Residual Treatment", desc: "Applied to harborage zones, baseboards, and entry points for ongoing protection." },
      { title: "Sanitation Guidance", desc: "Advice on food storage, moisture control, and clutter reduction to eliminate harborage conditions." },
    ],
    signs: [
      "Cockroaches seen during the day (usually indicates heavy infestation)",
      "Musty, oily odor in kitchen or bathrooms",
      "Droppings resembling coffee grounds or black pepper near food areas",
      "Egg casings (oothecae) in dark corners or behind appliances",
      "Smear marks on walls near moisture sources",
      "Dead cockroaches in kitchen or bathroom areas",
    ],
    process: [
      { step: "1", title: "Inspection", desc: "We inspect kitchens, bathrooms, utility areas, and all appliances to determine species and infestation level." },
      { step: "2", title: "Treatment", desc: "Gel bait, growth regulator, and residual insecticide applied to all harborage zones and entry points." },
      { step: "3", title: "Follow-Up", desc: "Re-inspection to confirm elimination and retreat as needed, often included in our service guarantee." },
    ],
    faqs: [
      { question: "How fast can cockroaches reproduce?", answer: "German cockroaches can go from 1 to 1,000 insects in about 3 months. Early treatment is critical." },
      { question: "Why do I only see cockroaches at night?", answer: "Cockroaches are nocturnal. If you're seeing them during the day, it usually indicates an overcrowded, established infestation." },
      { question: "Do I need to vacate my home for cockroach treatment?", answer: "Usually not. We use targeted gel baits that are safe for occupied homes. Your technician will advise on specific precautions." },
      { question: "How long until cockroaches are gone?", answer: "Most infestations show dramatic improvement within 1–2 weeks. A follow-up visit 2–4 weeks later ensures the infestation is fully resolved." },
    ],
    relatedServices: [
      { name: "Ant Control", slug: "ant-control" },
      { name: "Rodent Control", slug: "rodent-control" },
      { name: "Spider Control", slug: "spider-control" },
    ],
  },

  "mosquito-control": {
    slug: "mosquito-control",
    name: "Mosquito Control",
    heroHeading: "Mosquito Control San Diego, CA",
    heroSubheading: "Reclaim your outdoor spaces with professional mosquito barrier treatments that dramatically reduce mosquito populations.",
    heroImage: "/images/technician-grass.jpg",
    intro: "San Diego's warm, humid microclimates, especially near canyons, parks, and coastal areas, can produce significant mosquito populations. Beyond the nuisance, mosquitoes can transmit West Nile virus and other diseases. Our mosquito control program combines barrier sprays with source reduction to reduce mosquito populations by up to 90% in treated areas.",
    features: [
      { title: "Barrier Spray Treatment", desc: "Residual insecticide applied to vegetation, shrubbery, and resting sites around your yard." },
      { title: "Breeding Site Reduction", desc: "We identify and treat standing water sources where mosquitoes lay eggs on your property." },
      { title: "Larvicide Treatment", desc: "BTi larvicide applied to water features and drains to prevent larvae from developing." },
      { title: "Recurring Programs", desc: "Monthly or bi-monthly service keeps mosquito populations controlled throughout the season." },
    ],
    signs: [
      "Being bitten repeatedly when spending time outdoors",
      "Mosquitoes visible in shaded, vegetation-heavy areas of your yard",
      "Standing water in pots, gutters, bird baths, or low spots",
      "Buzzing sounds at dusk and dawn",
      "Mosquito larvae (wrigglers) visible in standing water",
      "Increased mosquito activity following rain",
    ],
    process: [
      { step: "1", title: "Inspection", desc: "We survey your property for adult mosquito resting sites and breeding locations." },
      { step: "2", title: "Treatment", desc: "Barrier spray applied to all vegetation and resting areas, plus breeding site treatment." },
      { step: "3", title: "Ongoing Protection", desc: "Monthly retreatments maintain protection throughout the mosquito season." },
    ],
    faqs: [
      { question: "How quickly does mosquito treatment work?", answer: "The barrier spray begins working immediately and provides 3–4 weeks of residual protection. You'll notice a significant reduction within 24–48 hours." },
      { question: "Is mosquito treatment safe for kids and pets?", answer: "Yes. Products are approved for residential use and safe once the treatment has dried, typically 30–45 minutes." },
      { question: "What can I do to reduce mosquitoes myself?", answer: "Empty standing water weekly (pots, gutters, bird baths, pet bowls). Trim overgrown vegetation and keep your lawn mowed." },
      { question: "Do you treat for Aedes mosquitoes?", answer: "Yes. We treat for all mosquito species present in San Diego, including Aedes aegypti (tiger mosquito), which can transmit Zika and dengue." },
    ],
    relatedServices: [
      { name: "Tick Control", slug: "tick-control" },
      { name: "Flea Control", slug: "flea-control" },
      { name: "Spider Control", slug: "spider-control" },
    ],
  },

  "flea-control": {
    slug: "flea-control",
    name: "Flea Control",
    heroHeading: "Flea Control San Diego, CA",
    heroSubheading: "Complete flea elimination for your home and yard using treatments timed with the flea life cycle.",
    heroImage: "/images/technician-customer.jpg",
    intro: "Fleas are more than just an itch, they can cause tapeworm infections, flea allergy dermatitis, and in severe cases, anemia. San Diego's mild climate means fleas can be active year-round. Effective flea control requires treating the home, yard, and your pets simultaneously, treating only one area allows fleas to reinfest from untreated sources. Our program covers all three.",
    features: [
      { title: "Interior Treatment", desc: "Residual insecticide and IGR applied to carpets, baseboards, upholstery, and pet bedding areas." },
      { title: "Exterior Treatment", desc: "Yard treatment targeting shaded areas where fleas rest and reproduce." },
      { title: "Insect Growth Regulator", desc: "Prevents flea eggs and larvae from developing, breaking the life cycle for lasting control." },
      { title: "Pet Treatment Coordination", desc: "We'll advise you on coordinating with your vet for proper on-pet flea treatment at the same time." },
    ],
    signs: [
      "Pets scratching, biting, or over-grooming",
      "Seeing tiny jumping insects on your pets, carpet, or furniture",
      "Small red bites on your ankles or lower legs",
      "Flea dirt (black pepper-like specks) on pet bedding or carpets",
      "Pets shaking their heads frequently",
      "Finding fleas on yourself after sitting on the floor",
    ],
    process: [
      { step: "1", title: "Inspection", desc: "We inspect all interior areas and the yard to determine flea harborage zones and infestation severity." },
      { step: "2", title: "Treatment", desc: "Simultaneous interior and exterior treatment with residual insecticide and IGR." },
      { step: "3", title: "Follow-Up", desc: "A follow-up treatment 2–3 weeks later addresses fleas emerging from eggs laid before treatment." },
    ],
    faqs: [
      { question: "Why do fleas come back after treatment?", answer: "Flea eggs take 1–3 weeks to hatch and are resistant to insecticides. A follow-up treatment 2–3 weeks after the first is essential to catch the new hatch." },
      { question: "Do I need to treat my pets too?", answer: "Yes. A full flea elimination requires treating the environment AND your pets. Consult your veterinarian for the appropriate on-pet treatment." },
      { question: "Do I need to leave my home during treatment?", answer: "Yes, we ask you, your family, and your pets to vacate for 2–3 hours during and after treatment to allow products to dry and settle." },
      { question: "Can fleas survive without pets?", answer: "Yes. Fleas can persist in carpets, furniture, and yards for months without a host. We treat the environment, not just where pets sleep." },
    ],
    relatedServices: [
      { name: "Tick Control", slug: "tick-control" },
      { name: "Mosquito Control", slug: "mosquito-control" },
      { name: "Spider Control", slug: "spider-control" },
    ],
  },

  "tick-control": {
    slug: "tick-control",
    name: "Tick Control",
    heroHeading: "Tick Control San Diego, CA",
    heroSubheading: "Protect your family and pets from tick-borne illness with professional yard and perimeter tick treatments.",
    heroImage: "/images/technician-webbing.jpg",
    intro: "Ticks are a growing concern in San Diego County, particularly in neighborhoods near canyons, nature preserves, and chaparral. Western black-legged ticks (deer ticks) in our region can carry Lyme disease. Our tick control treatments target the vegetation, leaf litter, and shaded areas around your property where ticks wait for a host.",
    features: [
      { title: "Perimeter & Yard Treatment", desc: "Residual treatment applied to the tick 'transition zone', where your lawn meets vegetation, brush, and fencing." },
      { title: "Vegetation Treatment", desc: "Treatment of low-growing shrubs, ground cover, and shaded areas where ticks harbor." },
      { title: "Recurring Protection", desc: "Seasonal or monthly service for properties near canyons, trails, or heavily wooded areas." },
      { title: "Prevention Guidance", desc: "Advice on landscaping practices and personal protection to minimize tick exposure." },
    ],
    signs: [
      "Finding ticks on yourself, children, or pets after outdoor activity",
      "Living near canyons, trails, or heavily vegetated areas",
      "Pets frequently coming in from outdoor areas",
      "Finding engorged ticks on animals or family members",
      "Skin rashes or bull's-eye pattern following an outdoor excursion",
      "Wildlife (deer, rabbits) frequently in your yard",
    ],
    process: [
      { step: "1", title: "Property Assessment", desc: "We walk your property to identify tick habitat, shaded areas, leaf litter, lawn edges, and vegetation zones." },
      { step: "2", title: "Targeted Treatment", desc: "Residual insecticide applied to all tick harborage areas and the lawn-vegetation transition zone." },
      { step: "3", title: "Ongoing Program", desc: "Monthly or bi-monthly retreatments for properties in high-risk areas near canyons or wildlands." },
    ],
    faqs: [
      { question: "What tick species are in San Diego?", answer: "Western black-legged ticks (potential Lyme carriers), American dog ticks, and brown dog ticks are most common in San Diego County." },
      { question: "When is tick season in San Diego?", answer: "Ticks are active year-round in San Diego's mild climate, but peak activity is typically from April through July, with a secondary peak in fall." },
      { question: "Is tick treatment safe for dogs?", answer: "Yes. Our treatments are safe for pets once dry, typically 30–45 minutes. We'll advise you on keeping pets off treated areas during the drying period." },
      { question: "How do I check for ticks?", answer: "After outdoor activity, check the scalp, behind ears, under arms, behind knees, and around the waistline. Shower within 2 hours of coming inside." },
    ],
    relatedServices: [
      { name: "Flea Control", slug: "flea-control" },
      { name: "Mosquito Control", slug: "mosquito-control" },
      { name: "Spider Control", slug: "spider-control" },
    ],
  },

  "beetle-control": {
    slug: "beetle-control",
    name: "Beetle Control",
    heroHeading: "Beetle Control San Diego, CA",
    heroSubheading: "Eliminate carpet beetles, bark beetles, and stored product beetles before they damage your home and belongings.",
    heroImage: "/images/technician-inspection.jpg",
    intro: "Beetles are one of the most diverse insect groups and a common pest problem in San Diego homes. Carpet beetles destroy natural fiber fabrics, rugs, and stored goods. Bark beetles attack ornamental trees. Stored product beetles infest pantry items like flour, cereal, and dried goods. Because beetle species behave very differently, accurate identification is the key to effective treatment.",
    features: [
      { title: "Species Identification", desc: "We identify the exact beetle species to target treatment precisely where they breed and feed." },
      { title: "Interior Treatment", desc: "Residual insecticide applied to infested areas including carpets, closets, and pantry zones." },
      { title: "Source Elimination", desc: "We locate and remove infested materials, nesting sites, and breeding sources." },
      { title: "Prevention Recommendations", desc: "Guidance on proper food storage, fabric protection, and exclusion to prevent reinfestation." },
    ],
    signs: [
      "Irregular holes or bare patches in wool rugs, upholstery, or clothing",
      "Shed larval skins or fecal pellets near fabrics or stored goods",
      "Small adult beetles near windows, lights, or in kitchen areas",
      "Infested pantry products like flour, cereal, or spices",
      "Damage to natural fiber items in closets or storage",
      "Small round holes in wooden furniture or structural wood",
    ],
    process: [
      { step: "1", title: "Inspection", desc: "We inspect infested areas, identify the beetle species, and locate breeding and feeding sites." },
      { step: "2", title: "Treatment", desc: "Targeted residual treatment applied to harborage zones, plus removal of infested source materials." },
      { step: "3", title: "Prevention", desc: "Recommendations on storage practices, exclusion, and monitoring to prevent recurrence." },
    ],
    faqs: [
      { question: "What types of beetles are common in San Diego homes?", answer: "Carpet beetles, drugstore beetles, cigarette beetles, and powderpost beetles are the most common species in San Diego residential properties." },
      { question: "Are beetles dangerous?", answer: "Most beetles are not dangerous to people, but carpet beetles and stored product beetles can cause significant damage to fabrics, food, and wooden structures." },
      { question: "How do beetles get inside?", answer: "Beetles commonly enter through open windows and doors, on cut flowers, or inside infested food products. Carpet beetles can also fly in from outside." },
      { question: "Do I need to throw away infested food?", answer: "Yes. Any pantry items showing signs of beetle infestation should be disposed of in a sealed bag. We'll advise on which items to keep vs. discard." },
    ],
    relatedServices: [
      { name: "Moth Control", slug: "moth-control" },
      { name: "Cockroach Control", slug: "cockroach-control" },
      { name: "Silverfish Control", slug: "silverfish-control" },
    ],
  },

  "carpenter-ant-control": {
    slug: "carpenter-ant-control",
    name: "Carpenter Ant Control",
    heroHeading: "Carpenter Ant Control San Diego, CA",
    heroSubheading: "Protect your home's structure from carpenter ants. We find the nest, eliminate the colony, and stop the damage.",
    heroImage: "/images/ants-windowsill.jpg",
    intro: "Carpenter ants are one of the most destructive pests in San Diego. Unlike termites, they don't eat wood, they tunnel through it to build galleries for their nests. Over time, this can cause serious structural damage to framing, fascia boards, window frames, and decking. Carpenter ants are large, often black or red-and-black, and are frequently seen foraging at night. Most infestations originate outdoors in dead trees, stumps, or wood in contact with soil before the satellite colony moves indoors.",
    features: [
      { title: "Nest Location", desc: "We track foraging trails and probe potential nest sites inside walls, under floors, and in structural wood." },
      { title: "Direct Colony Treatment", desc: "Targeted dust and residual insecticide injected into galleries and nest sites." },
      { title: "Exterior Perimeter Treatment", desc: "Barrier treatment around the foundation and entry points to stop foragers." },
      { title: "Moisture & Wood Recommendations", desc: "Advice on correcting moisture issues and removing wood-to-soil contact that attracts carpenter ants." },
    ],
    signs: [
      "Large black or red-and-black ants, especially at night",
      "Sawdust-like frass (wood shavings) near walls, window sills, or baseboards",
      "Rustling sounds inside walls, especially at night",
      "Winged carpenter ants (swarmers) inside your home in spring",
      "Soft or damaged wood in window frames, sills, or decking",
      "Foraging trails leading from outdoor wood to your home's interior",
    ],
    process: [
      { step: "1", title: "Inspection", desc: "We inspect inside and outside for foraging trails, satellite nests, moisture-damaged wood, and entry points." },
      { step: "2", title: "Treatment", desc: "Dust or liquid residual treatment injected into wall voids, galleries, and nest locations. Perimeter barrier applied." },
      { step: "3", title: "Prevention", desc: "Recommendations to fix moisture issues, remove wood debris, and trim vegetation away from the structure." },
    ],
    faqs: [
      { question: "Are carpenter ants as bad as termites?", answer: "They cause different but serious damage. Termites eat wood; carpenter ants hollow it out for nesting. Both require professional treatment and can cause costly structural damage if left untreated." },
      { question: "Can I treat carpenter ants myself?", answer: "Over-the-counter sprays kill foragers but rarely reach the nest. Professional treatment using dust injected into galleries is the most effective approach." },
      { question: "What attracts carpenter ants?", answer: "Moisture-damaged wood is the primary attractant. Fix leaks, replace rotted wood, and eliminate wood-to-soil contact to reduce risk." },
      { question: "How long does carpenter ant treatment take?", answer: "Elimination typically takes 1–3 weeks after treatment, depending on colony size. A follow-up inspection confirms the nest has been eliminated." },
    ],
    relatedServices: [
      { name: "Ant Control", slug: "ant-control" },
      { name: "Rodent Control", slug: "rodent-control" },
      { name: "Spider Control", slug: "spider-control" },
    ],
  },

  "centipede-millipede-control": {
    slug: "centipede-millipede-control",
    name: "Centipede & Millipede Control",
    heroHeading: "Centipede & Millipede Control San Diego, CA",
    heroSubheading: "Stop centipedes and millipedes from invading your home with targeted moisture control and perimeter treatments.",
    heroImage: "/images/technician-walkway.jpg",
    intro: "Centipedes and millipedes are moisture-loving arthropods that become a nuisance when they migrate indoors, especially during rainy periods or when organic material is disturbed outside. While millipedes are harmless detritivores, house centipedes can deliver a painful bite. Both indicate a moisture problem and a high population of other insects nearby. Our treatment targets both the pest and the conditions that attract them.",
    features: [
      { title: "Perimeter Barrier Treatment", desc: "Residual insecticide applied around the foundation, entry points, and moisture-prone zones." },
      { title: "Moisture Assessment", desc: "We identify moisture sources, drainage issues, and organic debris that attract these pests." },
      { title: "Interior Spot Treatment", desc: "Treatment of baseboards, crawl spaces, and areas where centipedes and millipedes are found." },
      { title: "Harborage Reduction", desc: "Recommendations to eliminate leaf piles, wood debris, and mulch against the foundation." },
    ],
    signs: [
      "Seeing centipedes or millipedes inside, especially in bathrooms and basements",
      "Large numbers of millipedes appearing after heavy rain",
      "Centipedes found in damp areas like under sinks or in crawl spaces",
      "Leaf litter, mulch, or wood piles against your home's foundation",
      "High moisture levels in crawl spaces, garages, or basement areas",
      "Millipede curling into a ball when disturbed",
    ],
    process: [
      { step: "1", title: "Inspection", desc: "We assess moisture conditions, harborage areas, and entry points around your property." },
      { step: "2", title: "Treatment", desc: "Residual barrier spray applied around the foundation, entry points, and interior harborage areas." },
      { step: "3", title: "Prevention", desc: "Recommendations to reduce moisture, remove debris, and seal entry points to prevent recurring invasions." },
    ],
    faqs: [
      { question: "Are centipedes dangerous?", answer: "House centipedes can bite if handled, but bites are rarely serious, similar to a bee sting. The main concern is discomfort and allergic reactions in sensitive individuals." },
      { question: "Why do I suddenly have so many millipedes?", answer: "Millipedes mass-migrate during or after heavy rain as they seek drier ground. Addressing moisture and debris near your foundation is the most effective long-term solution." },
      { question: "Will treating for centipedes also help with other pests?", answer: "Yes. Centipedes prey on other insects. A high centipede population often indicates a larger underlying insect problem. We treat both." },
      { question: "Do I need recurring service for centipedes and millipedes?", answer: "In most cases, a one-time treatment combined with habitat modifications is sufficient. Quarterly service helps if you live near canyons or heavily landscaped areas." },
    ],
    relatedServices: [
      { name: "Earwig Control", slug: "earwig-control" },
      { name: "Silverfish Control", slug: "silverfish-control" },
      { name: "Spider Control", slug: "spider-control" },
    ],
  },

  "cricket-control": {
    slug: "cricket-control",
    name: "Cricket Control",
    heroHeading: "Cricket Control San Diego, CA",
    heroSubheading: "Silence persistent cricket infestations with targeted interior and exterior treatments.",
    heroImage: "/images/technician-grass.jpg",
    intro: "Crickets are a common and frustrating pest in San Diego, especially in late summer and fall when populations peak. They invade garages, basements, and living spaces, and the constant chirping at night can make sleep impossible. Crickets also damage fabrics and paper products. In large numbers, they attract other predators like spiders and scorpions. Our treatments eliminate crickets at the source and create a barrier to keep them out.",
    features: [
      { title: "Exterior Perimeter Treatment", desc: "Residual insecticide applied around the foundation, doorways, garage, and entry points." },
      { title: "Interior Spot Treatment", desc: "Treatment of garages, basements, and interior harborage areas where crickets hide." },
      { title: "Harborage Reduction", desc: "Recommendations to eliminate wood piles, dense vegetation, and debris that attract crickets near your home." },
      { title: "Light Management Guidance", desc: "Advice on switching to yellow or sodium vapor lights outdoors, which attract fewer crickets than white lights." },
    ],
    signs: [
      "Chirping noises at night, especially in garages or basements",
      "Crickets jumping when you open garage doors or disturb storage areas",
      "Damage to fabric, paper, or cardboard items in storage",
      "Dead crickets accumulating around entry points",
      "Large numbers of crickets on exterior walls at night",
      "Cricket activity increasing in late summer and fall",
    ],
    process: [
      { step: "1", title: "Inspection", desc: "We assess entry points, harborage areas, and exterior conditions attracting crickets to your property." },
      { step: "2", title: "Treatment", desc: "Perimeter and targeted interior treatment with residual insecticide applied to all active and harboring areas." },
      { step: "3", title: "Prevention", desc: "Guidance on lighting, debris removal, and exclusion to reduce recurring cricket pressure." },
    ],
    faqs: [
      { question: "Why do I have so many crickets in fall?", answer: "Cricket populations peak in late summer and early fall as they seek warmth before cooler nights. San Diego's mild climate means this pressure can last well into November." },
      { question: "Are crickets harmful?", answer: "Crickets aren't dangerous but they're highly disruptive due to noise, and they damage fabrics, wallpaper, and stored goods. Large infestations also attract spiders." },
      { question: "Can crickets get into walls?", answer: "Yes, crickets can squeeze through small gaps and live inside walls and voids. We treat both interior and exterior to address all harborage zones." },
      { question: "How quickly does cricket treatment work?", answer: "You'll see a significant reduction within 24–48 hours. Perimeter treatments provide residual protection for several weeks." },
    ],
    relatedServices: [
      { name: "Spider Control", slug: "spider-control" },
      { name: "Earwig Control", slug: "earwig-control" },
      { name: "Cockroach Control", slug: "cockroach-control" },
    ],
  },

  "earwig-control": {
    slug: "earwig-control",
    name: "Earwig Control",
    heroHeading: "Earwig Control San Diego, CA",
    heroSubheading: "Get rid of earwigs invading your home with perimeter treatments and moisture management.",
    heroImage: "/images/technician-spraying.jpg",
    intro: "Earwigs are a common nuisance pest in San Diego, particularly in coastal and canyon-adjacent neighborhoods. They thrive in moist, dark environments and mass-invade homes during dry spells or after rain. While earwigs are harmless to people and pets, they're alarming to discover and can damage garden plants and seedlings. Effective control requires treating both the exterior harborage areas and the conditions that attract them.",
    features: [
      { title: "Perimeter Barrier Spray", desc: "Residual treatment applied around the foundation, entry points, and mulched or landscaped areas." },
      { title: "Moisture Source Identification", desc: "We identify and document moisture issues, over-irrigation, standing water, and drainage problems attracting earwigs." },
      { title: "Interior Treatment", desc: "Spot treatment of baseboards, bathrooms, and interior entry points where earwigs migrate inside." },
      { title: "Harborage Removal Guidance", desc: "Recommendations for reducing mulch depth, removing debris, and managing irrigation to eliminate earwig habitat." },
    ],
    signs: [
      "Earwigs found in bathrooms, kitchens, or under sinks",
      "Large numbers of earwigs under doormats, stones, or debris near the foundation",
      "Plant damage, including irregular holes in leaves and seedlings",
      "Earwigs appearing after rain events or irrigation",
      "Moist mulch, leaf litter, or wood piles against the foundation",
      "Earwigs entering through gaps under doors or around utility penetrations",
    ],
    process: [
      { step: "1", title: "Inspection", desc: "We assess moisture conditions, harborage areas, and entry points around the exterior and interior." },
      { step: "2", title: "Treatment", desc: "Perimeter barrier spray plus interior spot treatment targeting active harborage and entry zones." },
      { step: "3", title: "Prevention", desc: "Recommendations to manage irrigation, reduce ground cover against the structure, and seal entry points." },
    ],
    faqs: [
      { question: "Are earwigs dangerous?", answer: "No. Earwigs can pinch if handled but they do not sting, bite, or transmit disease. They're a nuisance pest, not a health threat." },
      { question: "Why are earwigs suddenly everywhere in my home?", answer: "Earwigs invade indoors en masse when outdoor conditions shift, typically after heavy rain or during dry spells. Addressing moisture and exterior harborage is key." },
      { question: "Do earwigs really go in ears?", answer: "This is a myth. Earwigs do not seek out human ears. The name comes from European folklore, not actual behavior." },
      { question: "How long does earwig treatment last?", answer: "A single perimeter treatment typically provides 4–8 weeks of protection. Quarterly service is recommended for homes with persistent moisture issues or heavy landscaping." },
    ],
    relatedServices: [
      { name: "Centipede & Millipede Control", slug: "centipede-millipede-control" },
      { name: "Silverfish Control", slug: "silverfish-control" },
      { name: "Cricket Control", slug: "cricket-control" },
    ],
  },

  "fly-control": {
    slug: "fly-control",
    name: "Fly Control",
    heroHeading: "Fly Control San Diego, CA",
    heroSubheading: "Eliminate house flies, fruit flies, and drain flies with targeted sanitation-based treatments.",
    heroImage: "/images/technician-customer.jpg",
    intro: "Flies are more than a nuisance in San Diego homes and businesses. House flies can carry over 100 pathogens including Salmonella and E. coli, contaminating surfaces and food on contact. Fruit flies breed rapidly in overripe produce and organic drain buildup. Drain flies emerge from the biofilm in slow or infrequently used drains. Persistent fly activity almost always points to a nearby breeding source that must be found and eliminated, not just sprayed.",
    features: [
      { title: "Breeding Source Identification", desc: "We locate the organic matter, drain buildup, or waste source where flies are breeding." },
      { title: "Drain Treatment", desc: "Enzymatic treatment applied to drains to eliminate the organic biofilm drain flies breed in." },
      { title: "Residual Interior Treatment", desc: "Applied to resting surfaces, entry points, and harborage areas to eliminate adult populations." },
      { title: "Exclusion Recommendations", desc: "Advice on door sweeps, window screens, and sanitation practices to prevent re-entry." },
    ],
    signs: [
      "House flies congregating around trash cans, drains, or food areas",
      "Fruit flies hovering over produce, trash bins, or near drains",
      "Small moth-like flies emerging from bathroom or kitchen drains",
      "Fly activity increasing indoors during warmer months",
      "Maggots in trash areas or around animal waste outdoors",
      "Persistent fly problem despite basic sanitation measures",
    ],
    process: [
      { step: "1", title: "Inspection", desc: "We identify the fly species and locate all breeding sources, drains, trash areas, organic waste, and food sources." },
      { step: "2", title: "Treatment", desc: "Targeted treatment of breeding sites, drain treatment for drain flies, and residual application to resting areas." },
      { step: "3", title: "Prevention", desc: "Sanitation recommendations and exclusion advice to eliminate conditions that attract and breed flies." },
    ],
    faqs: [
      { question: "Why do I have so many drain flies?", answer: "Drain flies breed in the organic film that builds up inside slow or unused drains. Cleaning drains with an enzymatic cleaner and improving drainage flow eliminates the breeding site." },
      { question: "Can I get rid of fruit flies with traps?", answer: "Traps catch adult fruit flies but don't eliminate the breeding source. Finding and removing overripe produce, disposing of recycling, and cleaning drains is essential." },
      { question: "Are flies dangerous in a home?", answer: "Yes. House flies land on food, utensils, and surfaces and can transfer pathogens like Salmonella, E. coli, and Shigella. Prompt treatment protects your family's health." },
      { question: "How long does fly treatment take to work?", answer: "Adult populations are dramatically reduced within 24–48 hours after treatment. Eliminating breeding sources prevents reinfestation within 1–2 weeks." },
    ],
    relatedServices: [
      { name: "Cockroach Control", slug: "cockroach-control" },
      { name: "Ant Control", slug: "ant-control" },
      { name: "Mosquito Control", slug: "mosquito-control" },
    ],
  },

  "moth-control": {
    slug: "moth-control",
    name: "Moth Control",
    heroHeading: "Moth Control San Diego, CA",
    heroSubheading: "Protect your clothing, fabrics, and pantry from clothes moths and pantry moths with targeted elimination.",
    heroImage: "/images/technician-inspection.jpg",
    intro: "Moths are a destructive but often overlooked pest in San Diego homes. Clothes moths silently damage wool, cashmere, silk, and other natural fiber garments, often going undetected until significant damage has already occurred. Pantry moths infest stored grains, flour, nuts, dried fruit, and pet food, and can spread quickly through kitchen cabinets. Early treatment is essential before populations grow and damage spreads.",
    features: [
      { title: "Species Identification", desc: "We identify whether you have clothes moths or pantry moths to apply the right targeted treatment." },
      { title: "Source Elimination", desc: "We locate and remove infested materials, larval webbing, and breeding sources." },
      { title: "Residual Treatment", desc: "Treatment of closets, storage areas, and pantry zones to eliminate larvae and prevent re-establishment." },
      { title: "Pheromone Monitoring", desc: "Pheromone traps placed to monitor moth activity and confirm elimination over time." },
    ],
    signs: [
      "Irregular holes or eaten patches in wool, cashmere, silk, or fur items",
      "Silky webbing, cocoons, or larval cases in closets or fabric storage",
      "Small moths flying in kitchen areas or near stored food",
      "Webbing or larvae inside pantry items like flour, cereal, or dried fruit",
      "Adult moths flying near closets or fabric storage areas at night",
      "Fine powdery frass near damaged fabric or food products",
    ],
    process: [
      { step: "1", title: "Inspection", desc: "We inspect closets, storage areas, and pantry items to identify the moth species and locate all infested materials." },
      { step: "2", title: "Treatment", desc: "Infested items are removed. Residual treatment applied to storage areas, closets, and cabinet interiors." },
      { step: "3", title: "Prevention", desc: "Recommendations for proper storage, cedar alternatives, and pheromone traps to prevent reinfestation." },
    ],
    faqs: [
      { question: "How do moths get into sealed closets?", answer: "Clothes moths are often introduced on secondhand clothing, dry cleaning, or antique textiles. Once inside, they can breed in dark, undisturbed areas for months." },
      { question: "Do cedar blocks actually work?", answer: "Fresh cedar repels adult moths but does not kill eggs or larvae. Cedar effectiveness fades after a few months and must be refreshed with cedar oil. Professional treatment is more reliable for active infestations." },
      { question: "How do I know if I have clothes moths vs. pantry moths?", answer: "Clothes moths are small, golden-tan, and avoid light. Pantry moths are slightly larger with a two-tone wing pattern and are found near food storage. We identify which species you have during inspection." },
      { question: "Should I throw away infested food?", answer: "Yes. Any pantry items showing signs of infestation should be sealed and discarded. Wipe down cabinet shelves before replacing with new, sealed containers." },
    ],
    relatedServices: [
      { name: "Beetle Control", slug: "beetle-control" },
      { name: "Silverfish Control", slug: "silverfish-control" },
      { name: "Cockroach Control", slug: "cockroach-control" },
    ],
  },

  "silverfish-control": {
    slug: "silverfish-control",
    name: "Silverfish Control",
    heroHeading: "Silverfish Control San Diego, CA",
    heroSubheading: "Eliminate silverfish from bathrooms, attics, and storage areas before they damage books, documents, and fabrics.",
    heroImage: "/images/technician-webs.jpg",
    intro: "Silverfish are fast-moving, moisture-loving insects that can survive for years in the right environment. They feed on starchy materials, including book bindings, wallpaper glue, cardboard, photographs, and natural fabrics. San Diego's microclimates, especially in coastal and canyon neighborhoods, provide the humidity silverfish need. Their presence typically signals a moisture issue that should also be addressed for lasting control.",
    features: [
      { title: "Targeted Residual Treatment", desc: "Applied to baseboards, cracks, closets, attic spaces, and bathroom areas where silverfish harbor." },
      { title: "Moisture Assessment", desc: "We identify the moisture conditions attracting silverfish and recommend corrections." },
      { title: "Attic & Crawl Space Treatment", desc: "Treatment of attic insulation and crawl space areas where silverfish commonly establish large populations." },
      { title: "Prevention Guidance", desc: "Advice on dehumidification, proper storage, and exclusion to eliminate silverfish habitat." },
    ],
    signs: [
      "Fast-moving silver insects in bathrooms, kitchens, or storage areas",
      "Yellowish stains or irregular feeding damage on paper and books",
      "Holes or scraped surfaces on wallpaper, book covers, or fabrics",
      "Shed skins, small and silvery, in dark undisturbed areas",
      "Silverfish found in bathtubs or sinks (they can't climb smooth surfaces)",
      "High humidity in attic, crawl space, or bathroom areas",
    ],
    process: [
      { step: "1", title: "Inspection", desc: "We inspect attic, crawl space, bathrooms, and storage areas to assess the extent of infestation and moisture levels." },
      { step: "2", title: "Treatment", desc: "Residual insecticide and dust applied to all harborage zones, including attic spaces and wall voids." },
      { step: "3", title: "Prevention", desc: "Moisture reduction recommendations and exclusion guidance for long-term control." },
    ],
    faqs: [
      { question: "Are silverfish harmful?", answer: "Silverfish do not bite or transmit disease, but they destroy irreplaceable items like books, photos, and important documents. Large infestations also indicate underlying moisture problems." },
      { question: "Why do I keep finding silverfish in my bathtub?", answer: "Silverfish fall into bathtubs and can't climb out due to the smooth surface. Their presence there means a larger population is living in nearby walls, cabinets, or the attic." },
      { question: "Does humidity control get rid of silverfish?", answer: "Reducing humidity significantly reduces silverfish populations over time. Using dehumidifiers and fixing leaks is an important part of the solution, but professional treatment addresses the existing population." },
      { question: "Can silverfish infest an entire home?", answer: "Yes. Silverfish can spread through walls, attics, and crawl spaces. Large populations are often found in attic insulation. Full-home inspection and treatment is recommended for established infestations." },
    ],
    relatedServices: [
      { name: "Earwig Control", slug: "earwig-control" },
      { name: "Centipede & Millipede Control", slug: "centipede-millipede-control" },
      { name: "Spider Control", slug: "spider-control" },
    ],
  },

  "stinging-pest-control": {
    slug: "stinging-pest-control",
    name: "Stinging Pest Control",
    heroHeading: "Stinging Pest Control San Diego, CA",
    heroSubheading: "Safe removal of wasp nests, yellow jacket colonies, and bee swarms from your San Diego property.",
    heroImage: "/images/technician-webbing.jpg",
    intro: "Wasps, yellow jackets, and hornets are common in San Diego and can pose a serious danger to your family, especially to those with allergies. Yellow jackets build underground and wall void nests and become highly aggressive in late summer and fall. Paper wasps build open nests under eaves and in shrubs. Mud daubers and cicada killers are usually solitary and less aggressive. Our stinging pest control services safely eliminate nests and colonies while protecting your family from stings.",
    features: [
      { title: "Nest Identification & Removal", desc: "We identify the species, locate all nest sites, and remove nests safely after treatment." },
      { title: "Wall Void Treatment", desc: "Yellow jackets building inside walls require dust treatment injected into the void followed by sealing." },
      { title: "Eave & Structure Treatment", desc: "Residual treatment applied around eaves, overhangs, and other common nesting sites." },
      { title: "Same-Day Service Available", desc: "Stinging pest calls are prioritized for same-day or next-day service given the safety risk involved." },
    ],
    signs: [
      "Visible paper or umbrella-shaped nests under eaves, in shrubs, or on fencing",
      "Wasps or yellow jackets flying in and out of a hole in the ground or wall",
      "Increased wasp activity around outdoor dining, trash cans, or sweet food",
      "Hearing buzzing sounds inside a wall or ceiling",
      "Yellow jacket nest visible in a tree, attic, or crawl space",
      "Being stung multiple times in the same area of your yard",
    ],
    process: [
      { step: "1", title: "Assessment", desc: "We locate all nest sites and identify the species to determine the correct treatment approach." },
      { step: "2", title: "Treatment & Removal", desc: "Nest treated with targeted insecticide. Nest removed once colony is eliminated. Wall voids treated with dust and sealed." },
      { step: "3", title: "Prevention", desc: "Recommendations for exclusion, sealing entry points, and deterrents to prevent future nesting." },
    ],
    faqs: [
      { question: "Can I remove a wasp nest myself?", answer: "We strongly advise against it. Disturbing a nest without proper equipment can trigger a mass attack. Yellow jackets inside walls are especially dangerous to treat without professional tools." },
      { question: "What's the difference between wasps and yellow jackets?", answer: "Yellow jackets are a type of wasp, but they're more aggressive, nest in larger colonies (up to 5,000), and are more likely to sting multiple times. Paper wasps are less aggressive and have smaller, open-cell nests." },
      { question: "When is stinging pest season in San Diego?", answer: "Yellow jacket colonies are largest and most aggressive in late summer and fall (August–October) when food sources become scarce. Paper wasps build nests from spring through fall." },
      { question: "Do you handle honey bee swarms?", answer: "We can assist with removal in many situations. Honey bees are a protected and beneficial species in California, so our approach depends on the location and situation. Call us to discuss." },
    ],
    relatedServices: [
      { name: "Mosquito Control", slug: "mosquito-control" },
      { name: "Spider Control", slug: "spider-control" },
      { name: "Tick Control", slug: "tick-control" },
    ],
  },

  "stink-bug-control": {
    slug: "stink-bug-control",
    name: "Stink Bug Control",
    heroHeading: "Stink Bug Control San Diego, CA",
    heroSubheading: "Keep brown marmorated stink bugs from invading your home and releasing their defensive odor indoors.",
    heroImage: "/images/technician-portrait.jpg",
    intro: "The brown marmorated stink bug has become an established pest in San Diego County and surrounding areas. These shield-shaped insects invade homes in large numbers in fall as they seek overwintering sites, congregating around windows, doors, and attic vents. When crushed or disturbed, they release a pungent, unpleasant odor. While stink bugs don't bite or cause structural damage, mass invasions are highly disruptive and difficult to control without professional exclusion and treatment.",
    features: [
      { title: "Exterior Barrier Treatment", desc: "Residual insecticide applied to the exterior walls, windows, eaves, and entry points before fall invasion begins." },
      { title: "Entry Point Exclusion", desc: "Identification and sealing of gaps around windows, doors, utility penetrations, and attic vents." },
      { title: "Interior Vacuuming Protocol", desc: "Guidance on safely removing stink bugs already inside without triggering their odor defense." },
      { title: "Seasonal Timing", desc: "Treatment is most effective in early fall before stink bugs begin actively seeking overwintering sites." },
    ],
    signs: [
      "Shield-shaped brown insects congregating on sunny exterior walls in fall",
      "Stink bugs appearing indoors near windows, light fixtures, or ceiling corners",
      "A strong, unpleasant odor in a room when bugs are disturbed",
      "Stink bugs clustering around attic vents or roofline areas",
      "Seeing stink bugs on outdoor vegetation in summer",
      "Stink bugs waking up and becoming active indoors during warm winter days",
    ],
    process: [
      { step: "1", title: "Assessment", desc: "We inspect entry points, assess infestation severity, and identify how stink bugs are gaining access." },
      { step: "2", title: "Treatment & Exclusion", desc: "Residual barrier treatment applied to all exterior surfaces. Entry points sealed to prevent indoor entry." },
      { step: "3", title: "Ongoing Prevention", desc: "Recommendations for seasonal treatment timing and continued exclusion maintenance." },
    ],
    faqs: [
      { question: "Are stink bugs dangerous?", answer: "No. Stink bugs don't bite, sting, or cause structural damage. Their only defense is the unpleasant odor they release when threatened, which can linger in fabrics and upholstery." },
      { question: "Why do stink bugs come inside in fall?", answer: "Stink bugs are not cold-hardy and seek sheltered, warm spaces to overwinter. Homes provide ideal conditions, so they gather on sunny exterior walls and try to enter through any gap." },
      { question: "What should I do if stink bugs are already inside?", answer: "Vacuum them up using a bag vacuum and immediately dispose of the bag outside. Avoid squishing them. We can advise on treating existing populations indoors." },
      { question: "When should I schedule stink bug treatment?", answer: "The most effective timing is late August through September, before stink bugs begin their fall migration. Treatment after they've already entered is less effective but still helps." },
    ],
    relatedServices: [
      { name: "Cricket Control", slug: "cricket-control" },
      { name: "Earwig Control", slug: "earwig-control" },
      { name: "Spider Control", slug: "spider-control" },
    ],
  },
};
